% project Euler 12 - Ondrej Budac
%
% The sequence of triangle numbers is generated by adding the natural 
% numbers. So the 7th triangle number would be 
% 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
% The first ten terms would be:
% 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
% Let us list the factors of the first seven triangle numbers:
%  1: 1
%  3: 1,3
%  6: 1,2,3,6
% 10: 1,2,5,10
% 15: 1,3,5,15
% 21: 1,3,7,21
% 28: 1,2,4,7,14,28
% We can see that 28 is the first triangle number to have over five divisors.
% What is the value of the first triangle number to have over five hundred divisors?

M=500;

ndiv = 1;
N = 1;
while ndiv <= M
    N = N + 1;
    a = N; 
    b = N+1;
    if mod(a,2) == 0, 
      a = a/2; 
    else
      b = b / 2; 
    end
    
    % Now T(n) = a * b, we compute number of divisors
    f = [factor(a), factor(b)];
    fs = unique(f);
    ndiv = 1;
    for i=1:numel(fs)
        ndiv = ndiv * (1+sum(f == fs(i)));
    end
end
res = N*(N+1)/2;